// AUTO-GENERATED from the Q1 2026 → Q1 2027 portfolio export (Growth team slice).
// Real initiative IDs are preserved so seeding stays idempotent (INSERT OR IGNORE).
// Edits made in-app persist; this seed only ever inserts rows that are absent.

export interface SeedInitiative {
  id: string
  title: string
  summary: string
  status: string
  priority: string | null
  theme: string | null
  year: number
  quarter: number
  effort_weeks: number | null
  impact_value: number | null
  impact_unit: string | null
  impact_kind: string | null
  owner_name: string | null
  objective: string | null
  is_bau: number
  is_required: number
  committed: number
  sort_order: number
}

export const SEED_INITIATIVES: SeedInitiative[] = [
  { id: "0c88d7f0-bb5c-42c2-88b9-00d034576803", title: "TGR Rebrand Phase 1", summary: "TGR Rebrand Phase 1 establishes the digital web foundation for The Great Room's brand launch by delivering location page updates, application form routing to the TGR HubSpot instance, and a new events landing page, all targeting a fixed go-live of July 1, 2026. Owned by the digital Growth team, this medium-priority, in-flight initiative supports TGR member acquisition and is estimated to drive $300K in revenue, with key dependencies on TGR brand assets, HubSpot configuration, and Marketing alignment.", status: "in_flight", priority: "high", theme: "revenue", year: 2026, quarter: 3, effort_weeks: 12, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: "Support RE growth", is_bau: 0, is_required: 0, committed: 1, sort_order: 0 },
  { id: "ef9d82ed-3728-44a9-ba33-72c0acc7b863", title: "Redesigned Search", summary: "", status: "proposed", priority: "critical", theme: "revenue", year: 2026, quarter: 4, effort_weeks: 16, impact_value: 1800618.72, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Accelerate time from source to signing", is_bau: 0, is_required: 0, committed: 0, sort_order: 1 },
  { id: "3289450d-ba02-45f4-a118-0b9d1d3ae8a2", title: "New Promotion Manager", summary: "The New Promotion Manager initiative replaces a slow, manual, and poorly governed promotion process with automation, validation rules, and oversight workflows—targeting a reduction in support-ticket dependency for pre-approved discounts while adding controls to prevent revenue leakage from unapproved custom discounts. Owned by Peter Feytser under the \"Spending more time on high-value work\" pillar, this medium-priority, M-sized effort is estimated to save 2,700 hours per year across Marketing, Sales, and Operations, with a target delivery of July 2026 pending prioritization.", status: "in_flight", priority: "critical", theme: "efficiency_ai_adoption", year: 2026, quarter: 3, effort_weeks: 12, impact_value: 2373.6, impact_unit: "hrs", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 1, sort_order: 2 },
  { id: "b6f2752c-3c6b-49bb-8f07-01cae05e74e7", title: "Indy new memberships testing", summary: "This project supports Nat's initiative to define and configure special independent subscription membership types, forming part of the broader effort to focus the team on high-value, strategic work. As standing run-the-business work, it sustains core membership operations without a targeted KPI by design.", status: "proposed", priority: "medium", theme: null, year: 2026, quarter: 4, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: null, is_bau: 1, is_required: 0, committed: 0, sort_order: 3 },
  { id: "0fa200db-6948-4b1d-9d01-a4afbd9c9425", title: "SEO/performance improvements", summary: "This project delivers ongoing technical and content SEO improvements guided by the Marketing team, keeping the site healthy and competitive as a core run-the-business responsibility. It sits within the broader initiative to spend more time on high-value work, ensuring foundational performance is maintained so the team can focus on higher-leverage activities.", status: "proposed", priority: "medium", theme: null, year: 2026, quarter: 4, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: null, is_bau: 1, is_required: 0, committed: 0, sort_order: 4 },
  { id: "2fd7f6f4-dbc2-4a40-9a1a-4dbb10fb7042", title: "MKT - self landing page / homepage updates through Devin, Vibe or Gemini", summary: "This project equips the Marketing team with AI-powered tools—Devin, Vibe, or Gemini—so they can autonomously implement and A/B test changes to the homepage and landing pages without relying on engineering support. As standing run-the-business work under the broader push to redirect team capacity toward higher-value initiatives, it enables MKT to iterate on web presence independently and on their own cadence.", status: "proposed", priority: "medium", theme: null, year: 2026, quarter: 4, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: null, is_bau: 1, is_required: 0, committed: 0, sort_order: 5 },
  { id: "1641344b-8988-4909-8af1-7ed5f8013a79", title: "Indy g2m launch marketing", summary: "This project delivers the go-to-market launch marketing for the Indianapolis location, driven by the urgency of a potential first-site signing as early as September. As standing run-the-business work, it covers the essential marketing execution needed to support a successful market entry whenever the location is confirmed.", status: "proposed", priority: "medium", theme: null, year: 2026, quarter: 4, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Adrien Devleschoudere", objective: null, is_bau: 1, is_required: 0, committed: 0, sort_order: 6 },
  { id: "5fc54531-9fcb-4160-9427-8700d7a1274c", title: "[TGR] Reservation-based access control", summary: "TGR Phase 2 automates door access permissions for reservation holders at TGR locations, eliminating manual intervention by tying the right access rights to the right location and reservation window. Targeting August 2026, this S-sized initiative is estimated to drive $100K in revenue through improved member experience and reduced operational overhead, with delivery contingent on TGR Phase 1 completion and access control system integration.", status: "in_flight", priority: "high", theme: "member_experience", year: 2026, quarter: 3, effort_weeks: 6, impact_value: 100000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Support RE growth", is_bau: 0, is_required: 0, committed: 1, sort_order: 7 },
  { id: "d7053c0c-0844-4992-8dd2-2a78518b090a", title: "Enable On-Demand in the EU", summary: "This initiative resolved the outstanding EU regulatory and financial-information compliance blockers that had prevented European members from accessing on-demand booking products, unlocking an expanded monetizable surface across the region. Delivered in May 2026, it targets $195K in annualized revenue from EU on-demand bookings and sits within the broader strategy to monetize open space for teams.", status: "done", priority: "medium", theme: "revenue", year: 2026, quarter: 2, effort_weeks: 4, impact_value: 195000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Monetize open space for teams", is_bau: 0, is_required: 0, committed: 1, sort_order: 8 },
  { id: "7b048305-6779-4d2d-8df3-da056f256caf", title: "Reserve Branding & Launch", summary: "Reserve Branding & Launch established a distinct brand identity and customer-facing frontend and marketing experience to present Reserve as a differentiated Industrious product offering in the market. Owned by the digital Growth team under Peter Feytser, the M-sized initiative has been delivered and carries an estimated $200K revenue impact.", status: "done", priority: "medium", theme: "revenue", year: 2026, quarter: 2, effort_weeks: 8, impact_value: 200000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 1, sort_order: 9 },
  { id: "924bfc1a-5ed8-4f37-9829-3b721b64c84b", title: "Member Experience Re-Platform", summary: "The Member Experience Re-Platform delivers the first release of a modernized member portal, replacing a legacy system that constrained product velocity, and lays the technical foundation for future work across membership types, onboarding, and account management. Completed in April 2026, the initiative targets $2.2M in revenue impact and 7,200 hours of operational savings across roughly 15,000 member accounts.", status: "done", priority: "medium", theme: "member_experience", year: 2026, quarter: 1, effort_weeks: 32, impact_value: 2200000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Monetize open space for teams", is_bau: 0, is_required: 0, committed: 1, sort_order: 10 },
  { id: "2ed7233b-e8c5-4a33-8839-57759a85cf51", title: "Indy Mobile Experience", summary: "The Indy Mobile Experience project evaluates mobile app capabilities being developed for the Indy brand to determine which are most valuable for Industrious members, then defines a roadmap to extend those features into the core Industrious experience. Owned by Peter Feytser and the digital Growth team, it will progress through a capability audit, member use case mapping, prioritization, and roadmap definition—with key open questions around which Indy capabilities are in development, their timeline, and the criteria for selecting features to carry forward.", status: "proposed", priority: "low", theme: "member_experience", year: 2026, quarter: 4, effort_weeks: 2, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: "We know our users and become the world's expert on studying what makes them feel human at work", is_bau: 0, is_required: 0, committed: 0, sort_order: 11 },
  { id: "68ca7dae-ca2d-493b-be6a-51773b34f03b", title: "Summer Cup Marketing Campaign", summary: "This XS initiative delivered web and mobile promotional modules for the time-bound Summer Cup campaign, integrating with a contractor-built competition landing page to drive member engagement and brand awareness. Owned by Peter Feytser under digital Growth, it completed in May 2026 against an estimated $50,000 revenue impact, with realized impact yet to be confirmed.", status: "done", priority: "medium", theme: "member_experience", year: 2026, quarter: 2, effort_weeks: 2, impact_value: 50000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 1, sort_order: 12 },
  { id: "9bc4d3ad-37d7-42f3-85c7-20ea6e30bf51", title: "Enterprise Pass On Demand", summary: "Enterprise Pass On Demand introduces a new subscription-style workspace access tier tailored for large enterprise teams that require recurring touchdown space but are underserved by existing day-pass and office subscription models, targeting $1.358M in incremental revenue. Owned by Digital Growth and scoped to include the enterprise on-demand pass product alongside its booking and access flow, this L-sized initiative is proposed for delivery in November 2026, pending prioritization and resolution of open questions around commercial model structure and eligible locations.", status: "proposed", priority: "high", theme: "revenue", year: 2027, quarter: 1, effort_weeks: 16, impact_value: 1358000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Monetize open space for teams", is_bau: 0, is_required: 0, committed: 0, sort_order: 13 },
  { id: "1bf223c5-748c-4482-a06b-32e5e84e7cc4", title: "[Indy] Network Access For All Members", summary: "", status: "proposed", priority: "critical", theme: "revenue", year: 2027, quarter: 1, effort_weeks: 10, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 0, sort_order: 14 },
  { id: "48ca7fd4-3f8e-4209-ad1c-a73a98d2c1b0", title: "Marketing: Homepage", summary: "The Homepage project redesigns and optimizes industriousoffice.com's highest-traffic entry point to sharpen value proposition clarity and drive stronger conversion from high-intent prospective members, supporting the broader goal of accelerating time from source to signing. Owned by Peter Feytser and targeting July 2026, the work spans redesign, messaging, and conversion optimization — with $462K in estimated revenue impact shared with the Solutions Pages initiative and attribution methodology still to be determined.", status: "to_do", priority: "high", theme: "revenue", year: 2026, quarter: 3, effort_weeks: 2, impact_value: 462000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Accelerate time from source to signing", is_bau: 0, is_required: 0, committed: 1, sort_order: 15 },
  { id: "8cfa595c-5a03-4348-95df-07e2317007a6", title: "Know Our Customer: Day 2 Questions", summary: "To deepen post-onboarding customer understanding, this initiative introduces a structured questionnaire sent to members at their 60-day mark, capturing how they are actually using Industrious once initial context has evolved beyond what onboarding data reflects. Owned by Peter Feytser within digital Growth and currently in flight toward a July 2026 target, the effort is estimated to save 500 hours of manual data collection and follow-up, directly advancing the strategic priority of becoming the world's expert on member experience at work.", status: "in_flight", priority: "high", theme: "data_systems", year: 2026, quarter: 3, effort_weeks: 4, impact_value: 500, impact_unit: "hrs", impact_kind: "decrease", owner_name: "Peter Feytser", objective: "We know our users and become the world's expert on studying what makes them feel human at work", is_bau: 0, is_required: 0, committed: 1, sort_order: 16 },
  { id: "cc71bac5-47b0-4c11-8502-abd516f15d7b", title: "Office Reservations 2.0", summary: "Office Reservations 2.0 is an XL-scoped initiative to deliver a next-generation member-facing booking experience — improving UX, reducing friction, and closing functionality gaps in the current office reservation flow — targeting an October 2026 launch after slipping from Q2. Projected to generate $500K in revenue through improved booking conversion, the initiative depends on Operations for workflow definitions and the reservation-service backend, with phased delivery under consideration given scope risk.", status: "proposed", priority: "high", theme: "revenue", year: 2026, quarter: 4, effort_weeks: 16, impact_value: 500000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Monetize open space for teams", is_bau: 0, is_required: 0, committed: 0, sort_order: 17 },
  { id: "e1afc0b9-3726-47fc-82f7-ae4af9994a0b", title: "Marketing: Blog Redesign", summary: "This initiative redesigns the blog's user experience to better serve SEO, content strategy, and reader engagement, strengthening organic acquisition as a top-of-funnel driver toward the \"accelerate time from source to signing\" priority. Owned by Digital Growth with Marketing and Design dependencies, the effort targets an estimated $460K revenue impact from improved organic traffic and blog-driven conversion, with prioritization and attribution methodology still to be confirmed.", status: "proposed", priority: "medium", theme: "revenue", year: 2026, quarter: 4, effort_weeks: 8, impact_value: 460000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Accelerate time from source to signing", is_bau: 0, is_required: 0, committed: 0, sort_order: 18 },
  { id: "988cfbad-e0ba-4f5b-9fd1-24a56c543a33", title: "Member Feedback Analytics", summary: "Member Feedback Analytics advances an existing NPS proof-of-concept into a production-grade system that surfaces actionable insights, threshold-based automatic alerts, and unified Admin Portal access to help operations and product teams detect churn risk earlier. The initiative targets $760K in retention-driven revenue and 8,400 hours of manual analysis saved, though it remains unscheduled and unprioritzed pending alignment on alert thresholds and the scope of what the prior POC already delivered.", status: "proposed", priority: "high", theme: "data_systems", year: 2027, quarter: 1, effort_weeks: 10, impact_value: 760000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "We know our users and become the world's expert on studying what makes them feel human at work", is_bau: 0, is_required: 0, committed: 0, sort_order: 19 },
  { id: "0803c5f6-14b7-4cbb-97d8-f7366eeea8a3", title: "[Indy] Member Activity Dashboard", summary: "This medium-priority initiative, owned by Peter Feytser, delivers a member-facing dashboard that provides a unified view for managing reservations across an expanding network of locations and booking types, directly supporting the monetization of open space for small teams. Targeting August 2026, the M-sized effort carries an estimated $367K revenue impact by reducing friction and improving member engagement as network access scales.", status: "to_do", priority: "high", theme: "member_experience", year: 2027, quarter: 1, effort_weeks: 8, impact_value: 367000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Monetize open space for teams", is_bau: 0, is_required: 0, committed: 1, sort_order: 20 },
  { id: "bf4ec1ff-978e-4d8a-9e9d-5d0c45ac1a30", title: "Marketing: Solutions Pages", summary: "This project creates or redesigns targeted marketing pages for key Industrious customer solutions and use cases, sharpening value proposition clarity and conversion by matching visitor intent to the right offering. Owned by Peter Feytser and currently proposed at medium priority, it carries an estimated $462K revenue impact tied to improved website conversion on solutions pages, with a target delivery of June 2026.", status: "done", priority: "high", theme: "revenue", year: 2026, quarter: 2, effort_weeks: 4, impact_value: 462000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Accelerate time from source to signing", is_bau: 0, is_required: 0, committed: 1, sort_order: 21 },
  { id: "9e031742-3fca-4991-8af7-5e28c9d2efb1", title: "Summer Friday Support Enablement", summary: "Summer Friday Support Enablement builds out the product experience and systems infrastructure needed to operationally run the Summer Fridays program, preventing manual workarounds and ensuring a consistent member experience. Delivered in May 2026 by the digital Growth team, the initiative targets $30,000 in revenue impact by removing product-side blockers from the program's execution.", status: "done", priority: "medium", theme: "member_experience", year: 2026, quarter: 2, effort_weeks: 4, impact_value: 30000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 1, sort_order: 22 },
  { id: "dcd63356-89d2-462b-99a5-2f3a3f0f8442", title: "Incremental Map Search Improvements", summary: "Incremental Map Search Improvements enhances location discovery on Industrious's website and member-facing surfaces by introducing distance-based sorting, U.S. zip code search, and prior-search-informed auto-complete — reducing friction in the booking and location-finding journey. The initiative, owned by Peter Feytser under the \"Spending more time on high-value work\" priority, was delivered in April 2026 with an estimated revenue impact of $2,000.", status: "done", priority: "medium", theme: "member_experience", year: 2026, quarter: 1, effort_weeks: 2, impact_value: 2000, impact_unit: "revenue", impact_kind: "increase", owner_name: "Peter Feytser", objective: "Spending more time on high-value work", is_bau: 0, is_required: 0, committed: 1, sort_order: 23 },
  { id: "d5b71e45-c6c7-4b39-aa74-5a2d0c1f7ea0", title: "[TGR] Meeting room overage billing", summary: "", status: "proposed", priority: null, theme: "member_experience", year: 2026, quarter: 3, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: "Support RE growth", is_bau: 0, is_required: 0, committed: 0, sort_order: 24 },
  { id: "389f8ded-fbcc-4381-a032-67e421f28cd2", title: "Marketing: Update Market Pages (SEO)", summary: "", status: "proposed", priority: null, theme: "revenue", year: 2026, quarter: 3, effort_weeks: null, impact_value: null, impact_unit: null, impact_kind: "increase", owner_name: "Peter Feytser", objective: "Accelerate time from source to signing", is_bau: 0, is_required: 0, committed: 0, sort_order: 25 },
]
